-- vim.g.copilot_no_tab_map = true
-- vim.api.nvim_set_keymap("i", "<C-k>", 'copilot#Accept("<CR>")', { silent = true, expr = true })
-- vim.keymap.set("n", "<leader>cpe", '<cmd>Copilot enable<cr>', { silent = true, expr = true })
-- vim.keymap.set("n", "<leader>cpd", '<cmd>Copilot disable<cr>', { silent = true, expr = true })
--
